name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: login to docker hub
      id: docker-hub
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        docker login -u $username -p $password 
    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/sample .
    - name: push the docker image
      id: push-docker-image
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/sample:latest

